### ISSUE TITLE
Trying to get an 80 column highlight to work with better-whitespace

### ISSUE THREAD

**Issue by erlandsona** [ntpeters/vim-better-whitespace#101]
I feel like this is similar to Issue #13 only having to do with me creating a custom "colorcolumn" @ 80 using the following in my .vimrc after I've set my colorscheme and after I've loaded the better-whitespace plugin.

```vim
" 80 Column - Not working for some reason???
hi OverLength ctermbg=darkred ctermfg=white guibg=#FFD9D9
function! OverLength() abort " not sure what abort is for here?
  match OverLength /\%>80v.\+/
endfunction

call OverLength()
augroup OverLength    
  autocmd!
  autocmd CursorMoved,
        \ CursorMovedI,
        \ InsertEnter,
        \ BufEnter,
        \ BufWrite * call OverLength()       
augroup END
```
Any suggestions on how to write the match to override just the offending lines and not all better-whitespace highlighting?

Ideally this should work in tandem with better-whitespace.

**Comment by Cimbali** [comment]
Calling `:match` replaces the previous match. I think it works
-  if you use `g:current_line_whitespace_disabled_soft=1` to use syntax highlighting instead of matching in better whitespace
- or if you use `:2match` (or `:3match`) instead of `:match` in your function `OverLength`, to match another of the 3 available match groups.

We probably should use `matchadd()` in the plugin instead, so we don't interfere with `:match`.

The `abort` argument makes the function abort as soon as an error is detected, so I don't think you need it on a single function call.

**Comment by erlandsona** [comment]
Wow! That's exactly what I was looking for!
Here's a screenshot in case anyone else runs into this in the future.

<img width="740" alt="screen shot 2019-01-21 at 2 41 20 pm" src="https://user-images.githubusercontent.com/10421138/51498028-be7bfd80-1d8a-11e9-8ec7-6570cec2a73c.png">

Notice on Line 18 where both better-whitespace and my OverLength function are working together in tandem.
