### ISSUE TITLE
Error generated when force saving file opened in read-only mode

### ISSUE THREAD

**Issue by mcrmonkey** [ntpeters/vim-better-whitespace#107]
When opening a file in vim in read only mode ( either via `view <filename>` or `vi -R <filename>` or `vim -R <filename>` ) and then attempting to write the file with the force option ( `:w!` ) an error is generated:

```
Error detected while processing function <SNR>StripWhitespaceCommand:
line    2:
```

I've traced this to line [206](https://github.com/ntpeters/vim-better-whitespace/blob/master/plugin/better-whitespace.vim#L206) in [plugin/better-whitespace.vim](https://github.com/ntpeters/vim-better-whitespace/blob/master/plugin/better-whitespace.vim) 

When the `echoerr` function is used the error is generated. If its switched for `echo` or `echohl` there is no error generated.

Issue looks to have appeared in commit: f5726c4bbe84a762d5ec62d57af439138a36af76 

Vim version: VIM - Vi IMproved 8.0
OS: Debian stretch
Loading via pathogen

**Comment by Cimbali** [comment]
Calling the `StripWhitespaceCommand` in a read only file intentionally causes the error you see.

You can use `StripWhitespace!` to force removing white space in such a file. Then saving (probably with StripWhitespaceOnSave disabled).

If you think the `:w! ` should also force stripping white space on top of force saving, that can be discussed.

**Comment by mcrmonkey** [comment]
Given how the file is opened I'd expect the error that the `echoerr` is trying to give, from vim itself, but the `echoerr` is throwing an explicit vim error.
...I'd think the same error would be thrown with the other `echoerr` on 215 too

If I forced the write with an `:w!` I'd expect it to follow the same process for `:w` as if the file was opened in a non-readonly state.

**Comment by Cimbali** [comment]
`echoerr` is the way to throw an error in vim. I think the fact that we are throwing it (when we can’t strip whitespaces on saving) instead of letting vim throw the error is fine. The rationale is of course that we don’t want so strip whitespaces (which has to occur before the file is saved), then have to undo it if the file is in fact not savable (because e.g. it is read-only).

I’ll see if it is possible to capture the bang `!` when saving.

**Comment by Cimbali** [comment]
Hmmm, I might have initially misunderstood your bug report.

Anyway, after having a quick look at this, I can’t reproduce the bug (using the version at commit f5726c4 and vim 8.1.1017).
- Saving readonly files with `:w` returns the E45 error as intended.
- Saving readonly files with `:w!` writes the the buffer to the file without an error, and correctly stripping whitespace.

**Comment by mcrmonkey** [comment]
I did a recording to show what I'm getting: https://asciinema.org/a/rF64uGMr0Dp8FjnzIkoeLMIjM

its all done in a docker container and I used this Dockerfile to create that container:

```Dockerfile
FROM debian:buster
RUN apt-get update -qq && apt-get install -qq vim git wget
WORKDIR /root
RUN mkdir -p ./.vim/autoload ./.vim/bundle
RUN wget -O /root/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
RUN git clone https://github.com/ntpeters/vim-better-whitespace ./.vim/bundle/vim-better-whitespace
RUN echo "execute pathogen#infect()\ncall pathogen#helptags()\nautocmd BufWritePre * StripWhitespace\n" > ./.vim/vimrc
```

I used debian:buster because it gave me a more up to date version of vim and set the vimrc at the bare minimum to reproduce

**Comment by mcrmonkey** [comment]
I also found mention of `echoerr` in https://google.github.io/styleguide/vimscriptfull.xml#Forbidden_Commands but couldn't find the full reasoning behind the statements for the use of `echoerr` though

**Comment by Cimbali** [comment]
So it seems the error message is printed, but prefixed with some sort of backtrace, when you force write (`:w!`). You should be able to confirm this using `:messages`.

The underlying problem seems to be that you are using `StripWhitespaceCommand` instead of `StripWhitespaceOnSave`, which correctly captures the force option (`!`, called `cmdbang`) when enabled through the plugin:

https://github.com/ntpeters/vim-better-whitespace/blob/f5726c4bbe84a762d5ec62d57af439138a36af76/plugin/better-whitespace.vim#L352-L354

Instead of your manual autocmd, try using `let g:strip_whitespace_on_save = 1` (or if you use the autocmd to restrict e.g. to some file types, try `autocmd FileType <desired_filetypes> EnableStripWhitespaceOnSave`).

**Comment by mcrmonkey** [comment]
ah-ha, my mistake!

The `autocmd` was a copy from someones vimrc from a while back I'm going to switch to using `let g:strip_whitespace_on_save = 1` as suggested.

> prefixed with some sort of backtrace

I think that's the source of the confusion here - I was seeing the correct error message flash up and remain in `:messages` but wasn't expecting the debug stuff

Thank you for your help :star:
