### ISSUE TITLE
Ignore "^ $" with gitcommit buffers (gitcommitDiff syntax group, verbose diff)

### ISSUE THREAD

**Issue by blueyed** [ntpeters/vim-better-whitespace#12]
With `git commit -v` (includes the patch) the single leading spaces in the verbose section are highlighted as errors.

The filetype is "gitcommit", and the syntax highlighting group for this section is `gitcommitDiff`.
Added/removed lines have the group `diffAdded` and `diffRemoved` additionally.

better-whitespace could
1. ignore errors for `^ $` in the gitcommitDiff part.
2. ignore any errors in `gitcommitDiff`, which is not also `diffAdded` or `diffRemoved`.

See also issue #3 (local settings) and #5 (filter/callback about what to handle).

**Comment by ntpeters** [comment]
Fixed in bf6d1ec

**Comment by blueyed** [comment]
This adds it to the blacklist, which looks like a sledgehammer workaround.

**Comment by ntpeters** [comment]
True enough, but I don't know of a way to exclude syntax groups from a match call.  I now added logic (7e17c6d) to not match within the `gitcommitDiff` group, but since this is only possible (to my knowledge) when defining a syntax highlight group it is only available when current line whitespace is disabled softly in the plugin.  Because this only partially solves the issue, I left the filetype `gitcommit` blacklisted.
