### ISSUE TITLE
Can't blacklist plugin for new buffers

### ISSUE THREAD

**Issue by oblitum** [ntpeters/vim-better-whitespace#130]
For new buffers, the test `!(empty(&buftype) && empty(&filetype))` fails, which causes `s:ShouldHighlight()` fallback to `g:better_whitespace_enabled`. Given that the test fails and avoids checking `g:better_whitespace_filetypes_blacklist`, there's no way to blacklist new untyped buffers, which also affects common output buffers that often have no `buftype` nor `filetype`.

**Comment by Cimbali** [comment]
IIRC we intentionally avoid setting anything for new buffers, as all buffers start as with no filetype.

Basically if you switch the plugin off for buffers that have no `buftype` or `filetype` it will necessarily be off for all buffers. There is no `FileType` event to confirm the buffer will not be getting a file type in the future.

I think your best bet right now is to:
1. Disable by default, i.e. set `g:better_whitespace_enabled = 0` 
2. Enable per-FileType `au FileType * EnableWhitespace`

Maybe listing the filetypes or looking up in that autocommand whether filetypes are in the blacklist.v

-----

The main issue we’re having is that once we decide whether a buffer should be enabled or not we can’t automatically re-decide when new information comes up (e.g. `FileType` event), since `b:better_whitespace_enabled` is already set. In particular, if I set manually a buffer to be on or off then following events should not affect that.

I think there could be 2 possible fixes. If you can work up a PR for any of those, that could be a good thing.
- option A), instead of returning `g:better_whitespace_enabled` from `ShouldHIghlight()` when `b:better_whitespace_enabled` is not set, return a new setting specifically for untyped buffers (if it is in fact an untyped buffer and `g:better_whitespace_enabled==1`).
- option B) track how the decision for `b:better_whitespace_enabled` was made in another variable, with several levels, and modify it if we get a “stronger” information:
  - (0) untyped buffers
  - (1) buftype set
  - (2) file type set
  - (3) file type `help` (would solve #128)
  - (4) manually set with `Enable/Disable/Toggle` commands

**Comment by oblitum** [comment]
Please check whether how we do this by default on [vim-lengthmatters](https://github.com/whatyouhide/vim-lengthmatters) is relevant here:

```vim
function! s:ShouldBeDisabled()
  for excluded in g:lengthmatters_excluded
    if &filetype =~# '^'.excluded.'$'
      return 1
    endif
  endfor
  return &buftype !=# ''
endfunction
```

<sub>[plugin/lengthmatters.vim#L52-L59](https://github.com/whatyouhide/vim-lengthmatters/blob/a86480f861c6cdcaa299704473a3b7fd5b47c70a/plugin/lengthmatters.vim#L52-L59)</sub>

What it does: if it's in the blacklist filetype list, it's not enabled (which includes the `''` filetype, which allows me to disable untyped filetypes independently). The fallback checks for buftype just to have it enabled only when it's empty (meaning it won't enable with filetypes not present in blacklist unless their buftypes are empty). There's a initial test for diff mode too, in another part of the code, so it's not enable in diff mode.

Not sure whether any of this applies here, but given that plugins have similar tasks, maybe it can help on the issue. With vim-lengthmatters at least I'm able to have it enable by default except on the files I blacklist, which also allows me it to be set on empty filetypes.
