### ISSUE TITLE
Detect whitespace in the terminal after neovim update

### ISSUE THREAD

**Issue by Cocossoul** [ntpeters/vim-better-whitespace#158]
Hello,

Since the neovim 0.8.0 update, the plugin shows the "trailing whitespaces" in red in the nvim integrated terminal.

It did not use to show them, and should not since trailing whitespace does not mean anything in the command line prompt/terminal output.

Thank you for your work !

**Comment by jaredh159** [comment]
yeah, i'm also noticing this problem. i was trying to figure out if there is a filetype for the terminal i could ignore, but stuck so far.  really appreciate the plugin!

**Comment by Cimbali** [comment]
This is strange behaviour in neovim. In `ShouldHighlight()` we check `empty(&buftype)` and on terminal windows we have `&buftype == 'terminal'`. I don’t have a ton of time to investigate it further at the moment unfortunately.

**Comment by adgoudz** [comment]
This workaround seems to be working for me:
```vim
augroup vimrc
  autocmd TermOpen * :DisableWhitespace
augroup END
```

**Comment by Cocossoul** [comment]
Worked for me too ! Thank you !

**Comment by Cimbali** [comment]
Actually in vim 9 whitespace is also enabled. Reproducible by doing:
- `:terminal`
- write whitespace
- go to normal mode (without switching buffers), e.g. with `<C-w>N`

Switching buffers triggers detection again. The fact it’s not shown when terminal mode is enabled is just because vim entirely renders the terminal through an external library and not by itself, so plugins don’t have an effect on that.

**Comment by eggbean** [comment]
> This workaround seems to be working for me:
> 
> ```viml
> augroup vimrc
>   autocmd TermOpen * :DisableWhitespace
> augroup END
> ```

This works fine on `nvim` but `TermOpen` doesn't seem to exist in `vim` and `gvim` unfortunately, so it brings up and error on startup.
