### ISSUE TITLE
Local settings per buffer / window

### ISSUE THREAD

**Issue by blueyed** [ntpeters/vim-better-whitespace#3]
It would be useful to have a command, which toggles the highlighting.

This woulds basically change the global and trigger the autocmd setup/deletion.

It might be useful to have buffer and window local setting, so that it could be toggled per buffer or window or both.

**Comment by ntpeters** [comment]
I realize it's been awhile since this issue was opened, but I've finally gotten some time to come back to it.
Honestly, I'm not entirely sure how to implement per buffer/window settings with the way this plugin is currently doing highlighting.  Do you have any thoughts?  If you know of a quick way to implement it, I'd happily accept a pull request as well.

**Comment by blueyed** [comment]
I have stopped working the plugin and use a custom method now.
I am not sure right now if that allows for buffer-local settings.

**Comment by ntpeters** [comment]
Alright, fair enough.  If you find that your method allows for this, or any other improvements, then I'd love to hear about it (or welcome a pull request).
