### ISSUE TITLE
Whitespaces highlighted in unite buffers even when unite filetype is blacklisted

### ISSUE THREAD

**Issue by Mat-R** [ntpeters/vim-better-whitespace#80]
### The Problem
From commit 8f488a4, whitespaces are highlighted in unite buffers. They were not before.

From what I read in the readme file, unite filetype shoud be blacklisted by default:
> This replaces the filetypes from the default list of blacklisted filetypes. The default types that are blacklisted are:
> ['diff', 'gitcommit', 'unite', 'qf', 'help', 'markdown']

### Vim version
VIM - Vi IMproved 7.4
Included patches: 1-1689
Extra patches: 8.0.0056

### Minimal .vimrc
```
call plug#begin('~/.vim/plugged')
Plug 'Shougo/unite.vim'
Plug 'ntpeters/vim-better-whitespace'
call plug#end()
```
### Screenshot before commit 8f488a4, using command `:Unite`
![2018-02-27-131351_1404x739_scrot](https://user-images.githubusercontent.com/36885389/36728236-600fd8f6-1bc0-11e8-9f1b-e243ce20b206.png)

### Screenshot after commit 8f488a4, using command `:Unite`
![2018-02-27-131427_1406x738_scrot](https://user-images.githubusercontent.com/36885389/36728204-47697226-1bc0-11e8-976e-01cb3f598388.png)

### Manual blacklisting in .vimrc
I also tried just in case to blacklist unite filetype in the .vimrc (even if it should already be blacklisted by default) with:
```
let g:better_whitespace_filetypes_blacklist=['unite']
```
but it did not change anything.

If you need me to provide more information, do not hesitate to ask.

**Comment by Cimbali** [comment]
This seems to be the same as #76. Basically we enter the buffer before loading it because it is plugin-generated content and not a file, so `BufWinEnter` is called before `FileType`.

We can only check the blacklist at `FileType` obviously, and we need to setup the auto commands every time we enter the buffer hence we need to have made up our mind at `BufWinEnter`.

Adding a third case for `b:better_whitespace_enabled` (**on / off / uninitialized**) that we would use as a default at `BufWinEnter` if `&filetype` is not set should fix this. Override this uninitialized value at `FileType`, fallback to `g:better_whitespace_enabled` if we encounter it when setting up auto commands.
